from .robot_linear_interpolation_walking import RobotLinearInterpolationWalking
from .robot_piecewise_constant_interpolation_walking import RobotPiecewiseConstantInterpolationWalking
from .robot_bezier_curves_interpolation_walking import RobotBezierCurveInterpolationWalking
from .virtual_robot_walking_static import VirtualRobotWalkingStatic
from .robot_spline_interpolation_walk import RobotSplineInterpolationWalking
from .virtual_robot_walking_animated import VirtualRobotWalkingAnimated